bits:
	g++ -c utils.cpp
	g++ -c GA_T.h
	g++ main_bits.cpp -o holi  utils.o

word:
	g++ -c utils.cpp
	g++ -c GA_T.h
	g++ main_words.cpp -o word utils.o

T2:
	g++ -c utils.cpp
	g++ -c GA_T.h
	g++ main_0-1_knapsack.cpp -o T2 utils.o